### ISSUE TITLE
All HTML items in one playlist are the same HTML item

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-playlist-new#64]
### What is the expected behavior?
I can add multiple items to the playlist template and have them handled as distinct items for scheduling, etc.

### What is the actual behavior?
Adding any number of HTML items to the same playlist in one template adds the same item.

### What steps can be taken to replicate the problem?

1. Start with a playlist template.
2. Add 1 HTML item, add some code.  
3. Add a second HTML item.  Add more code,
4. Look at the first item.  You'll have modified it too. 

Here's a video to talk you through it: https://drive.google.com/file/d/1xZy9_W45ZEO6cRnj7HoI3oVefxiFx07D/view?usp=drivesdk

**Comment by alex-deaconu** [comment]
@PatrickA-RiseVision this issue should now be fixed in apps. Closing. Thanks.
